name: Release Lexical

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  MIX_ENV: prod

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build and release Lexical
    env:
      COMMIT_SHA: "5ff7752d7c2917fc855242554a1f76a2e54a85a2"
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "25.2.1"
          elixir-version: "1.14.3-otp-25"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v3
        env:
          cache-name: cache-elixir-deps
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-

      - name: Install dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile

      - name: Build release
        run: mix release lexical

      - name: Archive release
        run: zip -r lexical-${{ env.COMMIT_SHA }}.zip _build/prod/rel/lexical

      - name: Create Git tag for commit
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.COMMIT_SHA }}",
              sha: context.sha
            })

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: lexical-${{ env.COMMIT_SHA }}.zip
          tag: ${{ env.COMMIT_SHA }}
          makeLatest: true
